#!/bin/bash


# bring up a pool as a service for testing


docker network create --driver overlay btcpooltest

docker config create eloipool.conf eloipool.config.py
docker service create --name pooltest --network btcpooltest \
    --config source=eloipool.conf,target=/eloipool/eloipool/config.py \
    --publish 3334:3334 \
    otaci/btctest-btc-pool


